### ISSUE TITLE
Does this implementation accept multiple hidden layers?

### ISSUE THREAD

**Issue by valeman** [csinva/imodelsX#10]
I was wondering if this implementation allowed for multiple hidden layers that is key in getting good performance.

**Comment by csinva** [comment]
I just pushed support for this :)

You'll need to update the package (`pip install imodelsx`), then can pass `hidden_layer_sizes` list for multiple layers (like sklearn's MLP). See the second cell of the [updated notebook](https://github.com/csinva/imodelsX/blob/master/demo_notebooks/kan.ipynb) for an example.
