### ISSUE TITLE
Class scores

### ISSUE THREAD

**Issue by valeman** [csinva/imodelsX#9]
How can one get class scores from KAN_Classifier? predict_proba returns 0 and 1 instead of class scores it seems.

**Comment by csinva** [comment]
Thanks for the question!

Sorry about that, original version didn't implement this properly, just pushed the latest version to pypi so predict_proba should work as expected (see the [notebook](https://github.com/csinva/imodelsX/blob/master/demo_notebooks/kan.ipynb)) for the working example.

To see the change, either run `pip install --upgrade imodelsx` or install from source.

**Comment by valeman** [comment]
Hi @csinva thats fantastic, thank you.
